# Generated by Django 4.2.29 on 2026-03-23 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="ingredients/")),
                ("sourced_from", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="IngredientNutrition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calories", models.DecimalField(decimal_places=1, max_digits=6)),
                ("protein", models.DecimalField(decimal_places=1, max_digits=5)),
                ("fat", models.DecimalField(decimal_places=1, max_digits=5)),
                ("carbs", models.DecimalField(decimal_places=1, max_digits=5)),
                ("fibre", models.DecimalField(decimal_places=1, max_digits=5)),
                ("per_grams", models.IntegerField(default=100)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition",
                        to="ingredients.ingredient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngredientBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("benefit", models.CharField(max_length=200)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="ingredients.ingredient",
                    ),
                ),
            ],
        ),
    ]
