# Generated by Django 4.2.29 on 2026-03-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent",
                    models.CharField(
                        choices=[
                            ("nutrition_decoder", "Nutrition Decoder"),
                            ("ingredient_story", "Ingredient Story"),
                            ("recipe_breakdown", "Recipe Breakdown"),
                        ],
                        max_length=50,
                    ),
                ),
                ("input_text", models.TextField()),
                ("output_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Agent Query",
                "verbose_name_plural": "Agent Queries",
                "ordering": ["-created_at"],
            },
        ),
    ]
